[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-nicolas-moscarda-1366617-unsplash
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-nicolas-moscarda-1366617-unsplash
GtkTheme=oomox-nicolas-moscarda-1366617-unsplash
IconTheme=oomox-nicolas-moscarda-1366617-unsplash
MetacityTheme=oomox-nicolas-moscarda-1366617-unsplash
