[Desktop Entry]
Type=X-GNOME-Metatheme
Name=oomox-7pd6lmjuo2t21
Comment=A partially sexual act; when a female (of any species; mostly humanoids) rubs the ears/lobes of a male Ferengi, creating sensual emotions and chemical reactions in the male (and sometimes in the female).
Encoding=UTF-8

[X-GNOME-Metatheme]
Name=oomox-7pd6lmjuo2t21
GtkTheme=oomox-7pd6lmjuo2t21
IconTheme=oomox-7pd6lmjuo2t21
MetacityTheme=oomox-7pd6lmjuo2t21
